### ISSUE TITLE
License? Etc?

### ISSUE THREAD

**Issue by FrostKnight** [Tomas-M/dynfilefs#2]
Was curious of licensing, whether its mit, gpl, etc...

Also, side note, but how good is it compared to ext4 and others feature wise?

Just curious

**Comment by Tomas-M** [comment]
License is GNU GPL v2, I've added file with license now.
Regarding features, dynfilefs provides a single virtual file of given size, which is then loop-mounted so you can make full ext4 filesystem on it before mount, and then mount it to get full ext4 features. Similarly if you format the loop file with XFS, you will get full xfs features, etc.
